export const DEFAULT_LOCALE = "en-US" as const;

export const adminText = {
  admin: {
    brand: { portal: "Admin Portal" },
    header: { subtitle: "Manage your store" },
    actions: {
      openMenu: "Open admin menu",
      closeMenu: "Close admin menu",
      approve: "Approve",
      reject: "Reject",
      delete: "Delete",
      approving: "Approving...",
      rejecting: "Rejecting...",
      deleting: "Deleting...",
      refresh: "Refresh",
      cancel: "Cancel",
      logout: "Log out",
      search: "Search",
      searchPlaceholder: "Search...",
    },
    navigation: {
      menu: "Main menu",
      dashboard: "Dashboard",
      banners: "Banners",
      guides: "Guides",
      products: "Products",
      combos: "Solution boxes",
      categories: "Categories",
      orders: "Orders",
      customers: "Customers",
      coupons: "Coupons",
      adminManagement: "Admin management",
      settings: "Settings",
    },
    dashboard: {
      eyebrow: "Maaniko store overview",
      welcome: "Welcome, {{name}}",
      subtitle: "Review the latest sales, orders, products, and customer activity.",
      revenue: "Total revenue",
      orders: "Total orders",
      products: "Total products",
      customers: "Total customers",
      recentOrders: "Recent orders",
      recentOrdersSubtitle: "Latest order activity",
      lowStock: "Low stock",
      newCustomers: "New customers",
      upFromLastMonth: "Up from last month",
    },
    management: {
      eyebrow: "Admin access",
      title: "All admins",
      subtitle: "Manage every administrator's role and status.",
      empty: "No admins found.",
      loadError: "Could not load admins.",
      forbidden: "This page is available to super admins only.",
      totalAdmins: "Total admins",
      approvedAdmins: "Approved",
      pendingAdmins: "Pending",
      rejectedAdmins: "Rejected",
      admin: "Admin",
      role: "Role",
      status: "Status",
      joined: "Joined",
      actions: "Actions",
      superAdminProtected: "Protected account",
      approved: "Admin approved and notification email sent.",
      rejected: "Admin request rejected.",
      deleted: "Admin account deleted.",
      confirm: {
        approve: { title: "Approve admin?", description: "{{name}} will be able to sign in to the Admin Portal." },
        reject: { title: "Reject admin?", description: "Confirm that you want to reject {{name}}." },
        delete: { title: "Delete admin?", description: "{{name}}'s account will be permanently deleted." },
      },
    },
    role: { admin: "Admin", superAdmin: "Super admin" },
    status: {
      pending: "Pending",
      approved: "Approved",
      rejected: "Rejected",
      processing: "Processing",
      delivered: "Delivered",
      cancelled: "Cancelled",
    },
    auth: {
      eyebrow: "Secure admin access",
      title: "Maaniko Admin Portal",
      subtitle: "Continue with an approved Google account.",
      google: "Continue with Google",
      loading: "Opening Google...",
      secure: "Only approved administrators can access this portal.",
      pending: "Your admin request is pending approval.",
      rejected: "Your admin request was rejected.",
      serverError: "Could not connect to the backend server.",
      oauthError: "Google sign-in could not be completed.",
      missingToken: "Google identity token was not returned.",
    },
    table: { orderId: "Order ID", customer: "Customer", status: "Status", total: "Total", actions: "Actions" },
    common: { viewAll: "View all", comingSoon: "This module will be available soon.", items: "items", management: "Management" },
  },
} as const;
